# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"
g=s.split()
print(g)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometer.".format (planet,diameter))


The diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [15]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d={
    'k1':[1,2,3, {
        'tricky':['oh','man','inception',{
            'target':[1,2,3,'hello']
        }]
    }]
}

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [8]:
import numpy as np
array=np.arange(20,36,1)
print(array)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [11]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [12]:
import pandas as pd
data=[10,20,30]
df=pd.DataFrame(data,columns=['Numbers'])
print(df)


   Numbers
0       10
1       20
2       30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [13]:
import calendar
c=calendar.TextCalendar(calendar.SUNDAY)
str=c.formatmonth(2023,1)
print(str)

    January 2023
Su Mo Tu We Th Fr Sa
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30 31



## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [14]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
daf = pd.DataFrame(lists)
print(daf)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
